---
- name: install httpd
  yum: name=httpd state=present

- name: copy httpd configure
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify: reload httpd

- name: httpd test page
  copy: src=index.html dest=/var/www/html/index.html

- name: remove nginx
  yum: name=nginx state=absent

- name: start httpd service
  service: name=httpd state=started enabled=yes

