---
- name: install php
  yum: name={{ item }} state=present
  with_items:
  - php-mysql
  - php
  - php-gd
  - gd
  - php-fpm

- name: start php-fpm service
  service: name=php-fpm state=started enabled=yes

- name: copy index.php
  copy: src=index.php dest=/usr/share/nginx/html/index.php

- name: copy php configure
  template: src=php.ini.j2 dest=/etc/php.ini
  notify: restart nginx


