---
- name: install mariadb
  yum: name={{ item }} state=present
  with_items:
  - mariadb-server
  - mariadb

- name: copy mariadb configure
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb
- name: start mariadb service
  service: name=mariadb state=started enabled=yes



