- name: install nginx
  yum: name={{ item }} state=present
  with_item:
  - epel-relese
  - nginx

- name: copy nginx configure
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: nginx test page
  copy: src=index.html dest=/usr/share/nginx/html/index.html

- name: remove httpd soft
  yum: name=httpd state=absent

- name: start nginx service
  service: name=nginx state=started enabled=yes


